--DROP TABLE "MOVIE" CASCADE CONSTRAINTS;
--DROP TABLE "likes" CASCADE CONSTRAINTS;
--DROP TABLE "member" CASCADE CONSTRAINTS;
--DROP TABLE "Mdetails" CASCADE CONSTRAINTS;
--DROP TABLE "guest" CASCADE CONSTRAINTS;
--DROP TABLE "board" CASCADE CONSTRAINTS;
--DROP TABLE "Ticketing" CASCADE CONSTRAINTS;

DROP TABLE "LIKES";
DROP TABLE "BOARD";

DROP TABLE "TICKETING";

DROP TABLE "MVGENRE";
DROP TABLE "MVACTOR";
DROP TABLE "MVDIRECTOR";
DROP TABLE "MVCOMPANY";

DROP TABLE "GENRE";
DROP TABLE "ACTOR";
DROP TABLE "DIRECTOR";
DROP TABLE "COMPANY";

DROP TABLE "MOVIE";

DROP TABLE "MEMBER";
DROP TABLE "GUEST";

desc director;
desc actor;
desc movie;

CREATE TABLE "GUEST" (
	"GCODE"	VARCHAR2(20)		NOT NULL,
	"GEMAIL"	VARCHAR2(100)		NULL,
	"GBIRTH"	VARCHAR2(100)		NULL,
	"GCONTACT"	NUMBER(20)		NULL,
	"GPWD"	VARCHAR2(100)		NULL
);
ALTER TABLE "GUEST" ADD CONSTRAINT "PK_GUEST" PRIMARY KEY (
	"GCODE"
);

CREATE TABLE "MEMBER" (
	"MCODE"	VARCHAR2(20)		NOT NULL,
	"MEMAIL"	VARCHAR2(100)		NULL,
	"MPWD"	VARCHAR2(100)		NULL,
	"MNAME"	VARCHAR2(100)		NULL,
	"MNICK"	VARCHAR2(100)		NOT NULL,
	"MBIRTH"	VARCHAR2(100)		NULL,
	"MGENDER"	CHAR(1)		NULL,
	"MCONTACT"	NUMBER(20)		NULL,
	"MADDR"	VARCHAR2(500)		NULL,
	"MTYPE"	NUMBER(10)		NULL,
	"MAUTHCODE"	NUMBER(10)		NULL
);
ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MCODE"
);

CREATE TABLE "MOVIE" (
	"MOVIECD"	VARCHAR2(20)		NOT NULL,
	"MOVIENM"	VARCHAR2(100)		NULL,
	"MOVIENMEN"	VARCHAR2(100)		NULL,
	"MOVIENMOG"	VARCHAR2(100)		NULL,
	"PRDTYEAR"	NUMBER(10)		NULL,
	"SHOWTM"	NUMBER(10)		NULL,
	"OPENDT"	NUMBER(10)		NULL,
	"TYPENM"	VARCHAR2(100)		NULL,
	"NATIONS"	VARCHAR2(100)		NULL,
	"CAST"	VARCHAR2(500)		NULL,
	"SHOWTYPES"	VARCHAR2(100)		NULL,
	"AUDITS"	VARCHAR2(100)		NULL,
	"POSTER"	VARCHAR2(500)		NULL
);
ALTER TABLE "MOVIE" ADD CONSTRAINT "PK_MOVIE" PRIMARY KEY (
	"MOVIECD"
);


CREATE TABLE "COMPANY" (
	"COMPANYNM"	VARCHAR2(100)		NOT NULL
);
ALTER TABLE "COMPANY" ADD CONSTRAINT "PK_COMPANY" PRIMARY KEY (
	"COMPANYNM"
);
CREATE TABLE "ACTOR" (
	"ACTORCD"	VARCHAR2(20)		NOT NULL,
	"ACTORNM"	VARCHAR2(100)		NULL,
	"ACTORNMEN"	VARCHAR2(100)		NULL
);
ALTER TABLE "ACTOR" ADD CONSTRAINT "PK_ACTOR" PRIMARY KEY (
	"ACTORCD"
);
CREATE TABLE "GENRE" (
	"GENRENM"	VARCHAR2(100)		NOT NULL
);
ALTER TABLE "GENRE" ADD CONSTRAINT "PK_GENRE" PRIMARY KEY (
	"GENRENM"
);
CREATE TABLE "DIRECTOR" (
	"DIRECTORCD"	VARCHAR2(20)		NOT NULL,
	"DIRECTORNM"	VARCHAR2(100)		NULL,
	"DIRECTORNMEN"	VARCHAR2(100)		NULL
);
ALTER TABLE "DIRECTOR" ADD CONSTRAINT "PK_DIRECTOR" PRIMARY KEY (
	"DIRECTORCD"
);


CREATE TABLE "MVCOMPANY" (
	"MOVIECD"	VARCHAR2(20)		NOT NULL,
	"COMPANYNM"	VARCHAR2(100)		NOT NULL
);
ALTER TABLE "MVCOMPANY" ADD CONSTRAINT "PK_MVCOMPANY" PRIMARY KEY (
	"MOVIECD",
	"COMPANYNM"
);
CREATE TABLE "MVACTOR" (
	"ACTORCD"	VARCHAR2(20)		NOT NULL,
	"MOVIECD"	VARCHAR2(20)		NOT NULL
);
ALTER TABLE "MVACTOR" ADD CONSTRAINT "PK_MVACTOR" PRIMARY KEY (
	"ACTORCD",
	"MOVIECD"
);
CREATE TABLE "MVGENRE" (
	"GENRENM"	VARCHAR2(100)		NOT NULL,
	"MOVIECD"	VARCHAR2(20)		NOT NULL
);
ALTER TABLE "MVGENRE" ADD CONSTRAINT "PK_MVGENRE" PRIMARY KEY (
	"GENRENM",
	"MOVIECD"
);
CREATE TABLE "MVDIRECTOR" (
	"DIRECTORCD"	VARCHAR2(20)		NOT NULL,
	"MOVIECD"	VARCHAR2(20)		NOT NULL
);
ALTER TABLE "MVDIRECTOR" ADD CONSTRAINT "PK_MVDIRECTOR" PRIMARY KEY (
	"DIRECTORCD",
	"MOVIECD"
);


CREATE TABLE "TICKETING" (
	"MOVIECD"	VARCHAR2(20)		NOT NULL
);
ALTER TABLE "TICKETING" ADD CONSTRAINT "PK_TICKETING" PRIMARY KEY (
	"MOVIECD"
);
CREATE TABLE "BOARD" (
	"BNO"	VARCHAR2(20)		NOT NULL,
	"MOVIECD"	VARCHAR2(20)		NOT NULL
);
ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BNO",
	"MOVIECD"
);
CREATE TABLE "LIKES" (
	"MOVIECD"	VARCHAR2(20)		NOT NULL,
	"MCODE"	VARCHAR2(20)		NOT NULL
);
ALTER TABLE "LIKES" ADD CONSTRAINT "PK_LIKES" PRIMARY KEY (
	"MOVIECD",
	"MCODE"
);

COMMENT ON COLUMN "MOVIE"."MOVIECD" IS '20124079';
COMMENT ON COLUMN "MOVIE"."MOVIENM" IS '광해, 왕이 된 남자';
COMMENT ON COLUMN "MOVIE"."MOVIENMEN" IS 'Masquerade';
COMMENT ON COLUMN "MOVIE"."MOVIENMOG" IS '광해, 왕이 된 남자';
COMMENT ON COLUMN "MOVIE"."PRDTYEAR" IS '2012';
COMMENT ON COLUMN "MOVIE"."SHOWTM" IS '131';
COMMENT ON COLUMN "MOVIE"."OPENDT" IS '20120913';
COMMENT ON COLUMN "MOVIE"."TYPENM" IS '장편';
COMMENT ON COLUMN "MOVIE"."NATIONS" IS '한국';
COMMENT ON COLUMN "MOVIE"."CAST" IS '광해,허균,중전,조내관...';
COMMENT ON COLUMN "MOVIE"."SHOWTYPES" IS '2D,3D';
COMMENT ON COLUMN "MOVIE"."AUDITS" IS '15세이상관람가';
COMMENT ON COLUMN "MOVIE"."POSTER" IS 'URL';


ALTER TABLE "LIKES" ADD CONSTRAINT "FK_MOVIE_TO_LIKES_1" FOREIGN KEY (
	"MOVIECD"
)
REFERENCES "MOVIE" (
	"MOVIECD"
);

ALTER TABLE "LIKES" ADD CONSTRAINT "FK_MEMBER_TO_LIKES_1" FOREIGN KEY (
	"MCODE"
)
REFERENCES "MEMBER" (
	"MCODE"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_TICKETING_TO_BOARD_1" FOREIGN KEY (
	"MOVIECD"
)
REFERENCES "TICKETING" (
	"MOVIECD"
);

ALTER TABLE "TICKETING" ADD CONSTRAINT "FK_MOVIE_TO_TICKETING_1" FOREIGN KEY (
	"MOVIECD"
)
REFERENCES "MOVIE" (
	"MOVIECD"
);

ALTER TABLE "MVCOMPANY" ADD CONSTRAINT "FK_MOVIE_TO_MVCOMPANY_1" FOREIGN KEY (
	"MOVIECD"
)
REFERENCES "MOVIE" (
	"MOVIECD"
);

ALTER TABLE "MVCOMPANY" ADD CONSTRAINT "FK_COMPANY_TO_MVCOMPANY_1" FOREIGN KEY (
	"COMPANYNM"
)
REFERENCES "COMPANY" (
	"COMPANYNM"
);

ALTER TABLE "MVACTOR" ADD CONSTRAINT "FK_ACTOR_TO_MVACTOR_1" FOREIGN KEY (
	"ACTORCD"
)
REFERENCES "ACTOR" (
	"ACTORCD"
);

ALTER TABLE "MVACTOR" ADD CONSTRAINT "FK_MOVIE_TO_MVACTOR_1" FOREIGN KEY (
	"MOVIECD"
)
REFERENCES "MOVIE" (
	"MOVIECD"
);

ALTER TABLE "MVGENRE" ADD CONSTRAINT "FK_GENRE_TO_MVGENRE_1" FOREIGN KEY (
	"GENRENM"
)
REFERENCES "GENRE" (
	"GENRENM"
);

ALTER TABLE "MVGENRE" ADD CONSTRAINT "FK_MOVIE_TO_MVGENRE_1" FOREIGN KEY (
	"MOVIECD"
)
REFERENCES "MOVIE" (
	"MOVIECD"
);

ALTER TABLE "MVDIRECTOR" ADD CONSTRAINT "FK_DIRECTOR_TO_MVDIRECTOR_1" FOREIGN KEY (
	"DIRECTORCD"
)
REFERENCES "DIRECTOR" (
	"DIRECTORCD"
);

ALTER TABLE "MVDIRECTOR" ADD CONSTRAINT "FK_MOVIE_TO_MVDIRECTOR_1" FOREIGN KEY (
	"MOVIECD"
)
REFERENCES "MOVIE" (
	"MOVIECD"
);

